# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  node: circleci/node@5.1.0
  docker: circleci/docker@2.2.0
  aws-cli: circleci/aws-cli@3.1.1 
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn run test
          name: Run tests

  build-and-push:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: ${DOCKER_LOGIN}/lab1
      - docker/push:
          digest-path: /tmp/digest.txt
          image: ${DOCKER_LOGIN}/lab1
  
  deploy:
    machine:
      enabled: true
    steps:
      - checkout
      - aws-cli/install
      - aws-cli/setup
      - run: 
          name: Setup key
          command: |
              echo "-----BEGIN RSA PRIVATE KEY-----" >> key.pem
              echo $SSH_KEY | tr " " "\n" >> key.pem
              echo "-----END RSA PRIVATE KEY-----" >> key.pem
              chmod 400 key.pem
      - run: 
          name: Connect through SSH
          command: |
              ssh -i "key.pem" ec2-user@${AWS_DOMAIN} "bash script.sh"

workflows:
  say-hello-workflow:
    jobs:
      - test
      - build-and-push:
          requires:
            - test
      - deploy:
          requires:
            - build-and-push